e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('login', views.login_page, name='login'),
    path('logout', views.logout_page, name='logout'),

    # category
    path('category/<str:category>', views.categories, name='category_with_argument'),
    path('categories', views.categories, name='categories'),

    # subcategory - products
    path('category/<int:category_id>/subcategory/<int:subcategory_id>', views.subcategory_products, name='subcategory_products'),

    # subcategory products - all, exclusive, best deals
    path('subcategories', views.subcategories, name='subcategories'),
    path('subcategories/<str:subcategory>', views.subcategories, name='exclusive_with_argument'),

    # product details
    path('product/<int:id>', views.product_details, name='product'),


    # add to cart - ajax request
    path('add_cart', views.add_to_cart, name='cart_add'),
    path('carts', views.cart_list, name='carts'),
    path('cart_delete/<int:cart_id>', views.cart_delete, name='cart_delete'),
    path('checkout', views.checkout, name='checkout'),

    # order
    path('create_order', views.create_order, name='create_order'),
    path('callback', views.callback, name='callback'),
    path('order_details/<int:order_id>', views.order_details, name='order_details'),
    path('order_list', views.order_list, name='order_list'),

    # upcoming
    path('user_profile', views.user_profile, name='user_profile'),
    path('favorite', views.favorite, name='favorite'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser, PermissionsMixin
import datetime
import os
from utils.constants import *
import uuid
from django.utils import timezone


# custom user manager
class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Email is required')

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(
            email,
            password=password,
            username=username,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


# custom user model
class User(AbstractUser, PermissionsMixin):
    username = models.CharField(max_length=50, blank=False)
    email = models.EmailField(max_length=255, unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def __str__(self):
        return self.email


# give file name while uploading
def get_file_name(request, file_name) -> str:
    date_time = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
    new_file_name = "%s%s" % (date_time, file_name)
    return os.path.join('uploads/', new_file_name)


# Extending model managers
class ProductQuerySet(models.QuerySet):
    def active_products(self):
        return self.filter(status=1)

    def exclusive_products(self):
        return self.filter(is_exclusive=1)


# Category model
class Category(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    image = models.ImageField(upload_to=get_file_name, null=True, blank=True)
    status = models.BooleanField(default=False, help_text="1-show, 0-hidden")
    description = models.TextField(max_length=500, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


# sub categories
class SubCategory(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_file_name, null=True, blank=True)
    description = models.TextField(max_length=500, null=False, blank=False)
    status = models.BooleanField(default=False, help_text="1-show, 0-hidden")
    trending = models.BooleanField(default=False, help_text="0-default, 1-trending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    subcategory = models.ForeignKey(SubCategory, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255, null=False, blank=False)
    product_image = models.ImageField(upload_to=get_file_name, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False)
    original_price = models.FloatField(default=0.00, null=False, blank=False)
    selling_price = models.FloatField(default=0.00, null=False, blank=False)
    description = models.TextField(max_length=500, null=False, blank=False)
    status = models.BooleanField(default=False, help_text="1-show, 0-hidden")
    trending = models.BooleanField(default=False, help_text="0-default, 1-trending")
    is_exclusive = models.BooleanField(default=False, help_text="0-default, 1-exclusive")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ProductQuerySet.as_manager()

    def __str__(self) -> str:
        return self.name


# shopping cart
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False)
    is_purchased = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'product')

    @property
    def total_final_cost(self):
        return self.quantity * self.product.selling_price

    @property
    def total_net_cost(self):
        return self.quantity * self.product.original_price

    def __str__(self) -> str:
        return str(self.quantity)


# create order
class Order(models.Model):
    payment_status = [
        ('completed', COMPLETED),
        ('pending', PENDING),
        ('in_progres', IN_PROGRES),
        ('error', ERROR)
    ]

    order_status = [
        ('shipped', SHIPPED),  # on transport
        ('delivered', DELIVERED),  # order completed
        ('in_progres', IN_PROGRES),  # packing in progres
        ('cancelled', CANCELLED)  # order cancelled
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_number = models.UUIDField(default=uuid.uuid4, editable=False)
    amount = models.FloatField(default=0.00, null=False, blank=False)
    street_name = models.CharField(max_length=100, null=False, blank=False)
    city = models.CharField(max_length=100, null=False, blank=False)
    district = models.CharField(max_length=100, null=False, blank=False)
    state = models.CharField(max_length=100, null=False, blank=False)
    pincode = models.CharField(max_length=100, null=False, blank=False)
    ordered_date = models.DateTimeField()
    payment_type = models.CharField(max_length=100, choices=PAYMENT_TYPES)
    payment_status = models.CharField(max_length=100, choices=payment_status)
    order_status = models.CharField(max_length=100, choices=order_status)
    provider_order_id = models.CharField(
        max_length=100, null=False, blank=False
    )
    payment_id = models.CharField(
        max_length=100, null=False, blank=False
    )
    signature_id = models.CharField(
        max_length=100, null=False, blank=False
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.order_number)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    amount = models.FloatField(default=0.00, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('order', 'product')

shop/forms/LoginForm.py
from ..models import User
from django import forms


class LoginForm(forms.Form):
    # form fields
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Your email id'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Please enter your password here'
    }))

    class Meta:
        model = User
        fields = [
            'email',
            'password',
        ]

shop/forms/orderForm.py
from ..models import Order
from django import forms
from utils.constants import *
from django.core.validators import RegexValidator


class OrderForm(forms.ModelForm):
    # form fields
    state = forms.ChoiceField(
        choices=STATES + [('', 'Select an option')],
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'state',
            'placeholder': 'Enter your state'
        })
    )

    district = forms.ChoiceField(
        choices=TAMIL_NADU_DISTRICTS + [('', 'Select an option')],
        widget=forms.Select(attrs={
            'class': 'form-control',
            'id': 'district',
            'placeholder': 'Enter the district'
        })
    )

    city = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter the city name'
        })
    )

    street_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'A - 75, Example start name'
        })
    )

    pincode = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Please enter you name here'
        })
    )

    payment_type = forms.ChoiceField(
        choices=PAYMENT_TYPES,
        widget=forms.RadioSelect()
    )

    class Meta:
        model = Order
        fields = [
            'state',
            'district',
            'city',
            'street_name',
            'pincode',
            'payment_type'
        ]

shop/forms/userRegisterationForm.py
from django.contrib.auth.forms import UserCreationForm
from ..models import User
from django import forms


# over writing the UserCreationForm
# TODO::add more user registration fields(customer user model)
class CustomUserForm(UserCreationForm):
    # form fields widgets
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'validationCustom02', 'placeholder': 'Please enter you name here'}
    ))

    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'name@example.com'}
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Please enter your password here'}
    ))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Please enter you password here'}
    ))

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

shop/templates/shop/order/callback.html
{% extends "shop/layouts/main.html" %}
{% block content %}
<div class="text-center" style="margin-top:20%">
    {% if status == "Success" %}
    <h2>THANKS YOUR PAYMENT HAS BEEN RECEIVED</h2>
    {% else %}
    <h2>SORRY, YOUR PAYMENT HAS BEEN FAILED</h2>
    {% endif %}
</div>
{% endblock %}

shop/templates/shop/order/create_order.html
{% extends "shop/layouts/main.html" %}
{% load static %}

{% block title %}
<title>Place your order | Majestic</title>
{% endblock title %}

{% block content %}
{% include "shop/includes/navbar.html" %}
{% include "shop/includes/message.html" %}


<div class="bg-holder overlay overlay-light"
     style="background-image: url('{% static 'images/gallery/header-bg.png' %}'); background-size: cover;">
</div>

<section class="py-6">
    <div class="container">

        <div class="row h-100">
            <div class="col-lg-7 mb-4">
                <h5 class="fs-3 fs-lg-5 lh-sm mb-3">Place your order</h5>
                <hr style="background-color:red; padding:2px; width: 10%"/>
            </div>
        </div>
        <div class="row h-100">
            <div class="col-6">
                <form method='post'>
                    {% csrf_token %}

                    {% if product %}
                    <!--Sent the product id and quantity-->
                    <input value={{ product.id }} type="hidden" name="product_id"/>
                    <input value={{ product.order_quantity }} type="hidden" name="order_quantity"/>
                    <input value={{ product.order_amount }} type="hidden" name="order_amount"/>
                    {% endif %}

                    <!--State-->
                    <div class="mb-3">
                        <label class="form-label">State</label>
                        {{ form.state }}
                        {% if form.errors.state %}
                        <div class="text-danger">
                            {{ form.errors.state }}
                        </div>
                        {% endif %}
                    </div>

                    <!--District-->
                    <div class="mb-3">
                        <label class="form-label">District</label>
                        {{ form.district }}
                        {% if form.errors.district %}
                        <div class="text-danger">
                            {{ form.errors.district }}
                        </div>
                        {% endif %}
                    </div>

                    <!--City-->
                    <div class="mb-3">
                        <label class="form-label">City</label>
                        {{ form.city }}
                        {% if form.errors.city %}
                        <div class="text-danger">
                            {{ form.errors.city }}
                        </div>
                        {% endif %}
                    </div>

                    <!--Street name-->
                    <div class="mb-3">
                        <label class="form-label">Street name</label>
                        {{ form.street_name }}
                        {% if form.errors.street_name %}
                        <div class="text-danger">
                            {{ form.errors.street_name }}
                        </div>
                        {% endif %}
                    </div>

                    <!--Pincode -->
                    <div class="mb-3">
                        <label class="form-label">Pincode</label>
                        {{ form.pincode }}
                        {% if form.errors.pincode %}
                        <div class="text-danger">
                            {{ form.errors.pincode }}
                        </div>
                        {% endif %}
                    </div>

                    <!--Payment type -->
                    <div class="mb-3">
                        <label class="form-label">Payment type</label>
                        {{ form.payment_type }}
                        {% if form.errors.payment_type %}
                        <div class="text-danger">
                            {{ form.errors.payment_type }}
                        </div>
                        {% endif %}
                    </div>

                    <!--Submit-->
                    <div class="mb-3">
                        <button class="btn btn-primary" type="submit">Place order</button>
                    </div>
                </form>
            </div>
            <div class="col-6">
                <div class="row h-100 mx-auto">
                    <div class="col-md-8 mx-auto">
                        <img src="{% static product.product_image %}" class="img-fluid rounded-start p-2" alt="...">
                    </div>
                    <div class="col-md-6 mx-auto">
                        <div class="card-body">
                            <h5 class="card-title" style="display: inline;">{{ product.name }}</h5>
                            {% if product.trending %}
                            <span class='badge bg-warning'>trending</span>
                            {% endif %}
                            <p class="card-text">{{ product.description }}</p>
                            <h6 class='my-2 text-danger'>Current price: Rs. <s>{{ product.original_price }}</s></h6>
                            <h5 class='my-2 text-info'>Selling price: Rs. {{ product.selling_price }} </h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--footer-->
    {% include "shop/includes/footer.html" %}

<script>
    $(document).ready(function() {
      $('#state').on('click', function() {
        var state = $(this).val();
        // district should be get form database with ajax request.
        var data = {{ districts|safe }}

        $("#district").empty();
        $.each(data, function(key, value) {
            $("#district").append($('<option>', {
                value: value,
                text: value
            }));
        });
      });
    });
</script>

{% endblock content %}

shop/templates/shop/order/order_details.html
{% extends "shop/layouts/main.html" %}
{% load static %}

{% block title %}
<title>Your order detail | Majestic</title>
{% endblock title %}

{% block content %}
{% include "shop/includes/navbar.html" %}
{% include "shop/includes/message.html" %}


<div class="bg-holder overlay overlay-light"
     style="background-image: url('{% static 'images/gallery/header-bg.png' %}'); background-size: cover;">
</div>

<section class="py-6">
    <div class="container">

        <div class="row h-100">
            <div class="col-lg-7 mb-4">
                <h5 class="fs-3 fs-lg-5 lh-sm mb-3">Order Details</h5>
                <hr style="background-color:red; padding:2px; width: 10%"/>
            </div>
        </div>
        <div class="row mb-4 mx-3">
            <div class="col-md-12">
                <b>Order number -</b> {{ order.order_number }}
                <div class="badge bg-primary">{{ order.order_status|capfirst }}</div>
                <div class='my-2'>Payment status: {{ order.payment_status|capfirst }}</div>

            </div>
        </div>
        {% for orderitem in order.orderitem_set.all %}
        <div class="row h-100 mx-auto">
            <div class="col-md-4">
                <img src="{% static orderitem.product.product_image %}" class="img-fluid rounded-start p-2"
                     alt="...">
            </div>
            <div class="col-md-8 p-3">
                <div class="card-body">
                    <h5 class="card-title" style="display: inline;">{{ orderitem.product.name }}</h5>
                    {% if orderitem.product.trending %}
                    <span class='badge bg-warning'>trending</span>
                    {% endif %}
                    <p class="card-text">{{ orderitem.product.description }}</p>
                    <h6 class='my-2'>Ordered price: Rs. {{ orderitem.amount }}</h6>
                    <h6 class='my-2'>Order quantity: Rs. {{ orderitem.quantity }}</h6>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<!--footer-->
{% include "shop/includes/footer.html" %}

{% endblock content %}

shop/templates/shop/order/order_list.html
{% extends "shop/layouts/main.html" %}
{% load static %}

{% block title %}
<title>Your orders | Majestic</title>
{% endblock title %}

{% block content %}
{% include "shop/includes/navbar.html" %}
{% include "shop/includes/message.html" %}


<div class="bg-holder overlay overlay-light"
     style="background-image: url('{% static 'images/gallery/header-bg.png' %}'); background-size: cover;">
</div>

<section class="py-6">
    <div class="container">
        <div class="row h-100">
            <div class="col-lg-7 mb-4">
                <h5 class="fs-3 fs-lg-5 lh-sm mb-3">Your orders</h5>
                <hr style="background-color:red; padding:2px; width: 10%"/>
            </div>
        </div>
        <div class="row h-100 mx-auto">
            {% for order in orders %}
            <div class="col-md-6 p-3">
                <div class="card-body">
                    <h5 class="card-title" style="display: inline;"><a href="{% url 'order_details' order.id %}">{{ order.order_number }}</a></h5>
                    <hr style="background-color:red; padding:1px; width: 10%"/>
                    <p class="card-text">Payment status: {{ order.payment_status }}</p>
                    <p class="card-text">Order status: {{ order.order_status }}</p>
                    <p class="card-text">Ordered date: {{ order.ordered_date }}</p>
                    <p class="card-text">Address:</p>
                    <div>
                        {{ order.street_name }} <br/>
                        {{ order.city }} <br/>
                        {{ order.district }} <br/>
                        {{ order.state }} <br/>
                        {{ order.pincode }} <br/>
                    </div>
                </div>
            </div>
            <div class="col-md-6 p-3">
                <div class="card-body">
                    <h5 class="card-title" style="display: inline;">Ordered products</h5>
                    <hr style="background-color:red; padding:1px; width: 10%"/>
                    <ul>
                        {% for order_item in order.orderitem_set.all %}
                            <li>{{ order_item.product.name }} - {{ order_item.product.quantity }} qty</li>
                        {% endfor %}
                    </ul>
                    <div>
                        Total amount :Rs. {{ order.amount }}
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>

        <!--Paginator-->
    {% include "shop/includes/pagination.html" with elements=orders %}
    </div>
</section>

<!--footer-->
{% include "shop/includes/footer.html" %}

{% endblock content %}

shop/templates/shop/order/payment.html
{% extends "shop/layouts/main.html" %}

{% block content %}

<form method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options = {
        key: "{{ razorpay_key }}",
        amount: "{{ amount }}", 
        currency: "{{ currency }}",
        description: "Test Transaction",
        // image: "https://example.com/your_logo",
        order_id: "{{ razorpay_order_id }}",
        callback_url: "{{ callback_url }}",
        redirect: true,
        prefill: {
            "name": "{{ request.user }}",
            "email": "{{ reqeust.user.email }}",
        },
        notes: {
            "address": "Razorpay Corporate Office"
        },
        theme: {
            "color": "#3399cc"
        }
    };
    var razorpay = new Razorpay(options);
    razorpay.open();
    </script>
    <input type="hidden" custom="Hidden Element" name="hidden">
</form>

{% endblock %}